gitlabform/gitlabform

gitlabform/configuration/projects_and_groups.py
PROBLEM
When setting a group configuration against a project that is in a subgroup (e.g. it has a slash in the name), GitLabForm fails with an error:
```
λ python C:\Users\x\AppData\Local\Programs\Python\Python36\Scripts\gitlabform ALL_DEFINED
>>> Processing ALL groups and projects defined in config
*** # of groups to process: 1
*** # of projects to process: 31
* [1/31] Processing: group/subgroup/project1
Traceback (most recent call last):
File "C:\Users\x\AppData\Local\Programs\Python\Python36\Scripts\gitlabform", line 6, in <module>
GitLabForm().main()
File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\gitlabform\gitlabform\core.py", line 136, in main
self.process_all(projects_and_groups)
File "C:\Users\x\AppData\Local\Programs\Python\Python36\lib\site-packages\git …
```
=> Enable support for subgroups

setup.py
tests_require instead of tests_requires See https://setuptools.readthedocs.io/en/latest/setuptools.html
=> setup.py: Fix naming of tests_require keyword

gitlabform/gitlab/groups.py
When running with ALL target, application is trying to list all
projects in all groups. But it crushes when there are groups
without any project.
This change fixes such errors.
=> Fix error on empty groups

gitlabform/gitlab/projects.py
When running with ALL target, application is trying to list lots of
items. But it crushes when there are some missing items which are
expected to be defined.
=> Fix error on empty items

gitlabform/configuration/core.py, gitlabform/configuration/projects_and_groups.py
When some sections are missing in config then app crashes with
ConfigNotFoundException exception.
But it should be allowed to skip groups or project settings if they
should be kept unmanaged.
This change fixes this behaviour.
=> Fix app crashing on missing config sections

.travis.yml, pytest.ini, setup.py
Added python37/python38 to tests and python38 to supported versions.
Removing debug from pytests and setting ignore on deprecation warnings which usually come from third party packages.
=> Adding python37 and python38 to tests and package information

gitlabform/gitlab/core.py, gitlabform/gitlab/projects.py, gitlabform/gitlabform/core.py, gitlabform/gitlabform/test/test_merge_request_approvers.py, run_gitlab_in_docker.sh
Partial fix for #68. This will be improved when https://gitlab.com/gitlab-org/gitlab/issues/198770 will be fixed.
=> Add new Merge Requests Approvers API support *with limitation to 1 user and 1 group*

config.yml
Followup to https://github.com/egnyte/gitlabform/issues/114
The example keys and values are taken from GitLab docs:
- https://docs.gitlab.com/ee/user/packages/container_registry/#use-the-cleanup-policy-api
=> Add example for container_expiration_policy_attributes

config.yml
The example config makes extensive use of "main" as the default project branch, but the setting isn't present in the example config.
It falls under the umbrella `project_config` (with a full list of settings available via GitLab documentation), but given that it's relevant to other options in the config file, I've added it here as well.
(This solves issue #182 that I opened in ignorance.)
=> Adds `default_branch` example to `project_config`

config.yml
This change adds a sample configuration that shows how to add
multiple CI CD variables with the same name but scoped to different
deployment environments.
closes #186
=> Add sample config for CI CD variables scoped to environment

gitlabform/gitlab/members.py, gitlabform/gitlab/projects.py, gitlabform/gitlabform/processors/project/members_processor.py
Fixes #101. Checks if the user is added with the correct access level and
expire date. If those values are not the ones defined by gitlabform
the user gets deleted if it's present and added again.
This commit also fixes #207, trying to use "expires_at" when setting
a user was making gitlabform to fail.
=> Add only users to project if they are not properly set

gitlabform/gitlab/core.py
to fix #219 and possibly other flows where
we expected 404 response.
=> If we expect 4xx, then fake {} as its body

gitlabform/gitlab/core.py, gitlabform/gitlabform/processors/project/merge_requests_processor.py
=> Remove call to delete_legacy_approvers in gitlab versions >= 13.11

CHANGELOG.md, docs/FEATURES_DESIGN.md
There seems to be some confusion between `projects_and_groups` and `groups_and_projects`
=> fix typo in docs

config.yml, gitlabform/gitlab/groups.py, gitlabform/gitlabform/processors/group/__init__.py, gitlabform/gitlabform/processors/group/group_shared_with_processor.py, gitlabform/gitlabform/test/__init__.py, gitlabform/gitlabform/test/conftest.py, gitlabform/gitlabform/test/test_group_shared_with.py
Hi,
This PR adds a new `group_shared_with` group level config, and code to maintain the list of groups that a group is shared with. It also includes acceptance tests, which pass (at least for me). The code is very much based on the code that maintains group user access.
I believe this fixes #150.
Please review the code, I'm happy to make any changes that might be required.
Many thanks,
Andrew Wilkinson (on behalf of Ocado Technology)
=> Add support for maintaining groups that are shared with other groups

gitlabform/gitlab/groups.py, gitlabform/gitlabform/processors/group/group_shared_with_processor.py, gitlabform/gitlabform/test/__init__.py, gitlabform/gitlabform/test/conftest.py, gitlabform/gitlabform/test/test_group_shared_with.py
Switch to using group path rather than group name when sharing groups with other groups. This allows subgroups to be shared with.
I wasn't able to reproduce #236, but this might fix it (and is probably a good idea anyway!)
Thanks,
Andrew Wilkinson (on behalf of Ocado Technology)
=> Switch to using group path rather than group name when sharing groups

gitlabform/gitlab/projects.py
Currently this api returns groups keyed by their name. This api is only used in MembersProcessor where we try and index it by the group path, so the groups are never found and deleted and readded on every run. This change switches to key them by path.
Fixes #240.
=> Update get_groups_from_project to return groups keyed by group_path

gitlabform/configuration/case_insensitivity.py, gitlabform/configuration/core.py, gitlabform/configuration/groups.py, gitlabform/configuration/projects_and_groups.py, gitlabform/core.py, gitlabform/filter.py, gitlabform/gitlab/core.py, gitlabform/input.py, gitlabform/output.py, gitlabform/processors/abstract_processor.py, gitlabform/processors/group/group_members_processor.py, gitlabform/processors/group/group_secret_variables_processor.py, gitlabform/processors/group/group_settings_processor.py, gitlabform/processors/group/group_shared_with_processor.py, gitlabform/processors/multiple_entities_processor.py, gitlabform/processors/project/deploy_keys_processor.py, gitlabform/processors/project/files_processor.py, gitlabform/processors/project/hooks_processor.py, gitlabform/processors/project/members_processor.py, gitlabform/processors/project/merge_requests_processor.py, gitlabform/processors/project/project_processor.py, gitlabform/processors/project/project_push_rules_processor.py, gitlabform/processors/project/project_settings_processor.py, gitlabform/processors/project/schedules_processor.py, gitlabform/processors/project/secret_variables_processor.py, gitlabform/processors/project/services_processor.py, gitlabform/processors/project/tags_processor.py, gitlabform/processors/util/branch_protector.py, gitlabform/processors/util/difference_logger.py, gitlabform/ui.py
by importing cli_ui.debug as verbose while logging.debug
as debug, we avoid the confusion when will each type of
output be printed when using --verbose or --debug flags.
Also shorten the calls by using more selective imports.
=> Cleaner output calls, especially verbose/debug

.github/workflows/linter-and-tests.yml
@gdubicki This PR tries to solve https://github.com/egnyte/gitlabform/pull/273#issuecomment-919367567
When we use `on.event.branches` like this :
```yaml
on:
push:
branches:
- '**'
pull_request:
types: [opened]
```
The workflow is only ran in a the base are evaluated. That means it'll only run workflow on branches in `egnyte/gitlabform` project. All unknown branch refs are ignored. The Workflow will also run when a PR is opened (just once) => will run for the `opened` event.
=> Run linter and tests workflow on every PR

CONTRIBUTING.md, README.md, config.yml, dev/run_gitlab_in_docker.sh, gitlabform/gitlab/branches.py, gitlabform/processors/util/branch_protector.py, tests/acceptance/test_branches.py, tests/acceptance/test_files.py
=> Add support of user under allow_to_push and allowed_to_merge in protect branches method

dev/run_gitlab_in_docker.sh
When I followed the [contributing guide](https://github.com/egnyte/gitlabform/blob/main/CONTRIBUTING.md#running-acceptance-tests-using-gitlab-instance-in-docker) to start GitLab in a container, I got error: "GITLAB_EE_LICENSE: unbound variable".
=> Fix GITLAB_EE_LICENSE: unbound variable

gitlabform/configuration/groups.py, gitlabform/configuration/projects_and_groups.py, gitlabform/gitlab/core.py, gitlabform/gitlab/projects.py, gitlabform/gitlab/users.py, gitlabform/processors/abstract_processor.py, gitlabform/processors/group/group_settings_processor.py, gitlabform/processors/multiple_entities_processor.py, gitlabform/processors/project/project_processor.py, gitlabform/processors/project/project_push_rules_processor.py, gitlabform/processors/project/project_settings_processor.py, gitlabform/processors/single_entity_processor.py, gitlabform/ui.py, pytest.ini, tests/acceptance/test_group_settings.py
* Add LRU cache for all requests to get ids entities
by name, as the ids don't change during a single
app run.
* Minimize debug logging duplication,
* Introduce SingleEntityProcess that generalizes editing
things that are single per project, f.e. settings
or push rules set. It does not edit entities if there
are not changes to be applied.
=> Faster run and less cluttered debug output

.gitignore, gitlabform/processors/abstract_processor.py, tests/acceptance/test_group_settings.py
=> Add missing case when entity update is needed

docs/IMPLEMENTATION_DESIGN.md, gitlabform/gitlab/branches.py, gitlabform/gitlab/core.py, gitlabform/gitlab/groups.py, gitlabform/gitlab/members.py, gitlabform/gitlab/merge_requests.py, gitlabform/gitlab/pipelines.py, gitlabform/gitlab/projects.py, gitlabform/gitlab/tags.py
as it happened a few times already that we didn't mark an API as using
pagination initially and it caused problems for some users. According
to GitLab's API docs (https://docs.gitlab.com/ee/api/#pagination)
the pagination "is available on all endpoints", so let's just pass
the for all GETs.
Fixes #354.
=> Always expect pagination for GETs

gitlabform/gitlab/schedules.py
This is a temporary workaround for a idempotency bug
in GitLab.
See issue #361.
=> Accept code returned when user is already an owner

setup.py
Reverts gitlabform/gitlabform#377
...because this pre-commit version ALSO requires > py3.6. :(
=> Revert "Bump pre-commit from 2.17.0 to 2.19.0"

docs/reference/integrations.md
The documentation was using `services` as key which is outdated. This was recently replaced with `integrations`. The tests were already updated in a prior commit but the documentation was forgotten. See here: https://github.com/gitlabform/gitlabform/commit/5bae26f09f1dca5307530db51376f90130d8d42e
=> Fix Integrations documentation

gitlabform/configuration/core.py
Hi, I'm getting acquainted with gitlabform, just trying to run it gives a kind of intimidating error msg:
> $ python gitlabform/run.py -c ...
🏗  GitLabForm version: 3.2.0 = the latest stable 😊
Reading config from file: ../../gitlab-config/config.yml
Traceback (most recent call last):
File "/Users/rzanella/oss/gitlabform/gitlabform/configuration/core.py", line 138, in get
current = current[token]
File "/Users/rzanella/oss/gitlabform/venv/lib/python3.9/site-packages/ruamel.yaml-0.17.21-py3.9.egg/ruamel/yaml/comments.py", line 927, in __getitem__
return ordereddict.__getitem__(self, key)
KeyError: 'token'
>
>During handling of the above exception, another exception occurred:
>
>Traceback (most recent call last):
File "/Users/rzanella/oss/gitlabform/gitlabform/run.py", line 9, in <module> …
=> Friendlier key not found exception msg

gitlabform/gitlab/members.py, gitlabform/processors/group/group_members_processor.py, gitlabform/processors/project/members_processor.py, tests/acceptance/conftest.py, tests/acceptance/standard/test_group_members_users.py, tests/acceptance/standard/test_members_add_group.py
instead of removing and re-adding them for a cleaner audit log.
Also stop allowing to pass user_id separately from username
- this is unnecessary complexity with little benefit (1 less API call in some rare cases).
Related to #466.
=> Refactor: edit users as members of projects and groups

gitlabform/processors/util/branch_protector.py, tests/unit/processors/test_branch_protector.py
The `get_current_permissions` method in `branch_protector.py` does not properly account for returned `access_levels` when they are set to `0`.
This PR just adds a verification that the `access_level` value is present, otherwise the if check becomes `if 0:` when the 0 access level is set, which equates to False, resulting in unnecessary reapplications of branch protection settings.
=> [Bug Fix] Fix protected branches current configuration access level fetching

gitlabform/configuration/transform.py, tests/acceptance/premium/test_merge_request_approvers.py, tests/unit/configuration/transform/test_merge_request_approvals_transformer.py
when a sole 'approvals_before_merge' settings is inherited/overwritten.
Also change an order in the transformed config from to put 'merge_requests_approvals' before 'merge_requests_approval_rules' (although I does not affect processing order, but it seems to be more logical).
=> Fix for old merge request syntax using inheritance

docs/index.md
Some minor update in the config samples in the docs so that they reflect the latest/current merge request approval syntax.
=> docs: update example in homepage to reflect latest config syntax

docs/running.md, gitlabform/__init__.py, gitlabform/gitlab/core.py, gitlabform/gitlab/groups.py, gitlabform/processors/__init__.py
and improve behavior in other cases when running as
a non-admin. In that case there is no point in trying
to get all groups or projects as you need at least
Reporter role to change their configuration.
Fixes: https://github.com/gitlabform/gitlabform/issues/509
=> Fix running with ALL when using gitlab.com

docs/contrib/local_development.md
* python3 directly does include the `venv` module, so no need to firstly install virtualenv in your user or even site packages anymore.
* With quotes around `.[test]` at least the `zsh` of macOS does try to evaluate this itself.
=> Fix docs about venv and test dependencies setup

docs/upgrade.md
=> upgrade to v3: mention MR approvals syntax change

dev/healthcheck-and-setup.sh
As of GitLab v16.0, all access tokens must have an expiry date. Otherwise the access token will not be created. This wasn't being done in the script that sets up a GitLab instances with an access token so that the token can be used for all acceptance tests via API calls. This worked fine before but started failing recently when latest version of GitLab was being used in the CI because the latest version is 16 and up. As a result, all the PR validations are failing because the acceptance tests are failing with '401 Unauthorized' error.
=> chore(dev/ci): set expiry date for access token

.github/workflows/linter-and-tests.yml, .github/workflows/pr-linter-and-tests.yml
to avoid failure of the whole pipeline on
intermitten codecov backend issues.
Uses a workaround provided by @LucasXu0
in https://github.com/codecov/codecov-action/issues/926.
=> Retry requests to codecov

.github/workflows/pr-linter-and-tests.yml, docs/reference/pipeline_schedules.md, gitlabform/processors/project/schedules_processor.py, tests/acceptance/standard/test_schedules.py
This change adds `enforce` support to pipeline schedule configuration. By adding `enforce: true`, unconfigured schedules can be deleted. This can help keep the gitlabform config and project's pipeline schedule's in sync.
closes #539
=> feat: add enforce support for pipeline schedule

docs/reference/tags_protection.md, gitlabform/gitlab/tags.py, gitlabform/processors/project/tags_processor.py, tests/acceptance/__init__.py, tests/acceptance/conftest.py, tests/acceptance/premium/test_tags.py
Currently `gitlabform` does not support [configuring tag protection](https://docs.gitlab.com/ee/user/project/protected_tags.html#configuring-protected-tags) using specific user(s) or group(s) as "Allowed to create". Only basic role can be set, such as: developer, maintainer, etc. Selecting individual user or group is a feature of Premium or Ultimate license.
This change adds the ability to configure tag protection to be set to individual users or groups. They can be set as a user/group ID or their names. For example with a config like below, a tag named `special-tag-blah` can only be created by either user `Jane.Doe`, or user whose ID is `123` or, users who are member of the group `foo-bar`.
```yaml
projects_and_groups:
group_1/project_1:
tags:
"v*":
protected: true
create_access_level: …
```
=> feat: add allowed_to_create support for tag protection

.github/workflows/pr-linter-and-tests.yml, tests/acceptance/conftest.py
This PR is related to #551 . In that PR the GitHub CI was fine, but after merging the change found out "type" issue in test fixture reported by `mypy`. See https://github.com/gitlabform/gitlabform/actions/runs/5617292516/job/15221155542
Not sure why the issue wasn't originally caught in the PR's CI but I had also missed running the `mypy` locally to validate it.
This PR addresses the type issue so that we have a clean codebase.
=> chore: fix incompatible type in test fixture

tests/acceptance/conftest.py, tests/acceptance/standard/test_members_enforce.py
This PR is related to `test__enforce_keep_bots` test case that intermittently fails but it does so quite often in GitHub Actions CI.
I was able to reproduce the issue locally too. The failure happens about 3 out of 5 runs of the test. In my local run, the failure was around asserting that the project has 2 members (i.e. test was getting 3 instead).
After a bit of debugging, I noticed that this test uses the same `project` fixture as the test (`test__enforce`) that runs before it. In that test, an additional user is added for validating that the `enforce: true` is working. Since the `project` fixture is scoped to a class, this project is also available to the `test__enforce_keep_bots` test.
When the intermittent issue does show up, the project's members still contains the user that was …
=> test: stabilize intermittent issue with enforce_keep_bots test

docs/contrib/local_development.md
I recently needed to setup the local dev environment for a premium feature that required setting up Gitlab with a license. It took a few trial and error for me to get it right. Thought I'd update the docs for clarity if it helps others in future.
=> docs: update local development instructions for clarity on env setup

.github/workflows/linter-and-tests.yml, .github/workflows/pr-linter-and-tests.yml, docs/requirements.md, setup.py
Python 3.7 has reached EOL (end of life) as of June 2023. See [status of python versions](https://devguide.python.org/versions/). We're already unable to update some of our dependencies as they have also dropped support for python 3.7. For example: #588, #591
This PR drops support for Python 3.7 by gitlabform.
closes #576
=> chore(python): drop support for python 3.7

gitlabform/gitlab/members.py, gitlabform/processors/group/group_members_processor.py, gitlabform/processors/project/members_processor.py, tests/acceptance/__init__.py, tests/acceptance/premium/test_branches_users_case_insensitive.py, tests/acceptance/standard/test_group_members_case_insensitive.py, tests/acceptance/standard/test_members_case_insensitve.py, tests/acceptance/standard/test_project_group_members_case_insensitive.py, tests/acceptance/standard/test_project_members_case_insensitve.py
Meddle with group and project membership checks to ensure that
usernames are case-insensitive. This change ensures that users
are not added again by mistake, causing an error where a given
user already exists within the repository.
=> fix(members): ensure group and project users are case-insensitive

docs/contrib/local_development.md, docs/contrib/releases.md
After doing a release of gitlabform for the very first time, thought I'd update the doc with complete step by step procedure for clarity. Hopefully we have more maintainers of gitlabform and this is helpful.
=> docs: update release process documentation for more clarity

gitlabform/gitlab/projects.py, gitlabform/processors/abstract_processor.py, gitlabform/processors/project/project_processor.py
This PR builds on top of #582 that provided the setup to use  `python-gitlab` library. Refactored the `project:archive` feature's implementation to use the `python-gitlab` library instead of internal methods that called GitLab's API endpoint.
closes #621
=> refactor: migrate project:archive feature to use python-gitlab library

docs/index.md
Hello,
First, thank you for your great project !
I found that links "[hierarchical configuration with inheritance, merging/overwriting and additivity](https://gitlabform.github.io/gitlabform/configuration_reference/#effective-configuration)" and "[pass some parameters as-is to GitLab APIs with PUT/POST requests](https://gitlabform.github.io/gitlabform/configuration_reference/#raw-parameters-passing)" on homepage https://gitlabform.github.io/gitlabform/#short-and-powerful-syntax are broken.
This PR fix it 😄
=> docs: fix broken links to references in homepage

gitlabform/util.py, tests/unit/test_utils.py
The datetime.date object used for access
expiration etc. is not supporting JSON serialization.
Trying to do this for debug output reasons
ends with an exception. The json.dumps() function
offers to specify a default handling of
unsupported types which is utilized here.
Resolves: #654
=> fix: json data with dates not serialized correctly

gitlabform/configuration/transform.py, gitlabform/processors/group/group_members_processor.py, gitlabform/processors/shared/protected_environments_processor.py, gitlabform/processors/util/difference_logger.py
The github action uses latest version of `black` when it runs. At the moment, the latest version of `black` is `24.1.1`, which wants to reformat some files that were previously fine as-is with version `23.x`.
Applied the formatting update the files using latest version of `black`.
closes #680
=> chore: formatting updates via latest version of black formatter

gitlabform/processors/project/hooks_processor.py, tests/acceptance/standard/test_hooks.py
The hooks processor was recently refactored in #635 . One of the change was to inspect and only update a hook when it is needed so that unnecessary api call/update is avoided. This was done by comparing hooks config with data from gitlab about project hooks.
The above fails when a hook config includes a `token` attribute. It's treated as secret and so it is not available in the gitlab data. The comparison fails and gitlabform produces error processing the project.
This PR fixes this issue by adding additional logic for hooks config with token. In this case an update is always done. Otherwise continue with existing logic of updating only if necessary. Updated test cases to validate it.
Fixes #685
=> fix: hooks processing fails when config includes token

gitlabform/__init__.py, gitlabform/gitlab/core.py
as suggested in https://setuptools.pypa.io/en/latest/pkg_resources.html
plus a tiny refactoring (simplify some names)
=> Replace deprecated code with Python 3.8-compatible one

dev/Dockerfile
Runs the container as user different from root for security reasons.
See https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html#rule-2-set-a-user
=> runs container as non-root

gitlabform/__init__.py, gitlabform/processors/abstract_processor.py, tests/acceptance/__init__.py, tests/acceptance/standard/test_running.py, tests/acceptance/standard/test_transfer_project.py
Fixes #728.
Update `abstract_processor.py` to not overwrite `project_or_project_and_group` when determining if a project is being transferred
=> fix: error when running with --noop and --output-file parameter and config contains project to be transferred

gitlabform/processors/project/schedules_processor.py
* process all schedules and not only the first 20
* get_all takes all schedules without using paging
Fixes this problem with our project with 57 schedules:
```
/gitlabform/gitlabform/processors/project/schedules_processor.py:26: UserWarning: Calling a `list()` method without specifying `get_all=True` or `iterator=True` will return a maximum of 20 items. Your query returned 20 of 56 items.
```
=> fix: process all schedules and not only the first 20

gitlabform/__init__.py, tests/acceptance/standard/test_transfer_project.py
Gitlabform will error when it tries to process a project that has already been transferred:
```
Warning: Error occurred while processing project ... failed - expected code(s) [200], got code 405 & body: '{"message":"Non GET methods are not allowed for moved projects"}'
```
This happens when running with ALL_DEFINED target and if there's config that includes the original project path, ie.:
```
projects_and_groups:
group/*:
...
group/subgroup/*:
...
group/project-a:
project:
transfer_from: group/subgroup/project-a
...
```
This PR add handling for this scenario.
=> fix: add improved error handling when processing transferred project

gitlabform/gitlab/groups.py, gitlabform/processors/group/group_settings_processor.py
Use python gitlab lib for group settings. 
Ran existing acceptance tests in standard folder and they pass.
=> refactor: migrate group settings processor to python-gitlab library 

README.md, dev/run_gitlab_in_docker.sh, docs/reference/pipeline_schedules.md, tests/acceptance/standard/test_schedules.py
- Tests required to be updated due to enforcement fixes in GL 17
- Documentation updated; pre-existing rules on GL API are now being enforced correctly
- relates to #764
=> test: update pipeline_schedules tests for GitLab 17

docs/contrib/local_development.md, docs/features.md, docs/reference/job_token_scope.md, gitlabform/processors/project/__init__.py, gitlabform/processors/project/job_token_scope_processor.py, tests/acceptance/conftest.py, tests/acceptance/standard/test_job_token_scope.py
=> feat: support CI/CD job token scope api

docs/requirements.md
Minor update about ability to use pyenv if one's OS does not have a required version of Python.
=> docs: Add info about and link to pyenv

gitlabform/gitlab/python_gitlab.py, tests/unit/gitlab/test_python_gitlab.py
- can't be tested by our test suite as standing up a container counts as self-managed not saas
=> fix: path for member_roles in saas

docs/reference/pipeline_schedules.md, gitlabform/processors/project/schedules_processor.py, tests/unit/processors/test_schedules_processor_extended_cron_pattern.py
* Allow an extended syntax for minutes, hours and weekdays in definitions.
* Replace `H(N1-N2)` for minutes and hours with a project stable number between N1 and N2 including both values.
* Specifying letter `H` only is the same as `H(0-59)` for minutes, `H(0-23)` for hours and H(0-6)' for weedays.
* This allows to specify one single cron expression which may be reused in all projects of a group.
* Add some common aliases like '@nightly' etc.
Refs: #455
=> feat: enhanced cron expressions

gitlabform/processors/project/schedules_processor.py
* Order is important in _create_schedule_with_variables.
* Cron expression in `entity_config` must be replaced *before* it is decomposed into scheduled data.
Refs: #455
=> fixup! feat: enhanced cron expressions

docs/contrib/local_development.md, docs/features.md, docs/index.md, mkdocs.yml
Couple of new features released in recent versions were not available in the navigation menu used for browsing various feature specific configuration options. This PR adds those docs to the nav list. Also added some minor chores/fixes to the docs.
closes #782
=> docs: add new feature docs to navigation of docs about various configuration options

docs/running.md, gitlabform/__init__.py, gitlabform/processors/__init__.py, gitlabform/processors/abstract_processor.py, gitlabform/processors/project/variables_processor.py, gitlabform/processors/single_entity_processor.py, gitlabform/processors/util/difference_logger.py, tests/unit/processors/test_difference_logger.py
Partially solves #290
Just looking to clear up the output a bit, especially when working with larger numbers of projects. In my case, we can often be working with 10s or hundreds of projects at a time. Limiting the output to just what is changing (more similar to Terraform's `plan` output) helps keep things easier to read :)
Both `--verbose` and `--diff-only-changed` must be set to have the desired output.
I'd personally hope that we could work towards a way to see this kind of output without having to set `--verbose`, but I'll circle back on that later :smile: 
Config I used to generate my output:
```yaml
config_version: 3
projects_and_groups:
fancy-group-isa/*:
project_settings:
default_branch: main
visibility: public
```
Command I ran:
```shell
gitlabform -n -v --diff-only-changed -c …
```
=> Adding flag to only print settings that are being changed

tests/acceptance/standard/test_integrations.py
As noted in #816 , temporarily removing redmine from integration tests till we can come back and more fully include testing that does not cause conflicting issue tracking integrations.
=> fix #816 Cleanup tests

gitlabform/processors/group/group_saml_links_processor.py, tests/acceptance/premium/test_group_settings.py
fixes #823 
Not using correct saml group link from the config to check existing links and it ends up treating them all as new. 
Also fixed link enforce with the correct group name.
=> fix: saml group link idempotent update

gitlabform/__init__.py, gitlabform/gitlab/groups.py, gitlabform/lists/groups.py, gitlabform/lists/projects.py, tests/acceptance/__init__.py
solves https://github.com/gitlabform/gitlabform/issues/613
This feature is disabled by default and can be enabled with the cli flag `--recurse-subgroups` or `-r`.
=> run gitlabform for a single group and all its subgroups

gitlabform/processors/project/members_processor.py
In our DWP environment, we are getting errors with member processing as not all members are being returned, and members are attempted to be added that are already present in projects. This change should allow all members to be listed, and therefore no members that are already present should be attempted to be added :) 
https://github.com/gitlabform/gitlabform/issues/836
=> fix: return all members when listing for member processor

gitlabform/processors/util/difference_logger.py, tests/unit/processors/test_difference_logger.py
Found that if there were no changes to make and `--diff-only-changed` was set, that we'd run into the following error:
```
Warning: Error occurred while processing project <project name/path>, exception:
max() iterable argument is empty
```
This is due to the fact that with [here](https://github.com/gitlabform/gitlabform/blob/main/gitlabform/processors/util/difference_logger.py#L43) we set `changes` to a potential empty list. The empty list causes the call to `max()` [here](https://github.com/gitlabform/gitlabform/blob/main/gitlabform/processors/util/difference_logger.py#L57-L59) to error out.
Opting to simply return early with an empty string when changes is empty to avoid running into the error.
=> fix error when --diff-only-changed is set, but no changes are present

gitlabform/processors/project/variables_processor.py
This MR fix this error:
```
Config AFTER transformations:
%YAML 1.2
---
projects_and_groups:
group/project:
variables:
enforce: true
MY_VARIABLE:
variable_type: env_var
raw: true
protected: false
masked: false
key: MY_VARIABLE
value: '18'
Running in dry-run mode...
....
Variables in group/project in configuration:
Warning: Error occurred while processing project group/project, exception:
'bool' object is not subscriptable
Traceback (most recent call last):
File "/home/webadm/.local/lib/python3.11/site-packages/gitlabform/__init__.py", line 482, in run
self.project_processors.process_entity(
File "/home/webadm/.local/lib/python3.11/site-packages/gitlabform/processors/__init__.py", line 31, in process_entity
processor.process(
File …
```
=> dry-run mode - fix error on project variables with enforce option

gitlabform/processors/project/members_processor.py, tests/acceptance/conftest.py, tests/acceptance/standard/test_members.py
This fixes the issue #836 for the condition when member list is paginated.
=> fix: iterates through project list to check and add members

.github/workflows/tests-standard.yml, docs/requirements.md, gitlabform/processors/util/labels_processor.py, setup.py
BREAKING CHANGE: but note that the next older Python
version support drop (when 3.13 stable will be released)
will NOT be treated as a breaking change anymore.
https://github.com/gitlabform/gitlabform/issues/754
=> chore!: stop supporting Python older than 3.12 

gitlabform/processors/multiple_entities_processor.py, gitlabform/processors/project/__init__.py, gitlabform/processors/project/branches_processor.py, tests/acceptance/__init__.py, tests/acceptance/premium/test_branches.py, tests/acceptance/premium/test_branches_users_case_insensitive.py, tests/acceptance/premium/test_merge_request_approval_rules.py, tests/acceptance/premium/test_protected_environments.py, tests/acceptance/standard/test_branches.py, tests/acceptance/standard/test_files.py
There are certain features in GitLab that are related or dependent. For example:
- branch protection can be configured with granular option such as specific user or group is allowed to push or allowed merge.
- environment protection can be configured same way so that selected user or group is allowed to deploy.
- environment protection approval rules can also have similar setup as well
- merge request approval rules can be configured to select specific user or group
All of the above are dependent on membership of the project. The selected user must be a member with appropriate access or the project must be shared with the selected group.
Currently, GitLabForm's processing of various config happens in the order where membership config happens after processing branch protection setting and …
=> fix: project settings failing to apply because membership config is not processed

gitlabform/processors/multiple_entities_processor.py, gitlabform/processors/project/branches_processor.py, tests/acceptance/premium/test_branches.py, tests/acceptance/premium/test_branches_users_case_insensitive.py, tests/acceptance/premium/test_merge_request_approval_rules.py
Previously a change was relased in v4.0.1 that fixed the ordering of config processor. One change included in it increased the overall execution time of gitlabform if the config contained members for a project. This was due to acceptance tests failing when those users were being referenced in other config sections. The change added delays causing the execution time increase.
After further investigation, it seems that delay is only needed in the acceptance tests because gitlabform does not actually create users. The tests setup creates new users and in that case a small delay is needed.
This change removes the unnecessary delay that was included in the runtime of gitlabform. The delay has been added to necessary tests setup.
=> perf: reduce execution time due to project members config

gitlabform/processors/project/branches_processor.py, gitlabform/processors/project/files_processor.py, tests/acceptance/standard/test_branches.py
This pull request refactors some of the logic to do with protected branches to fix a bug introduced in `4.0.2` of gitlab form. This bug is specifically to do with trying to protect a branch in gitlab using a wildcard. 
It adds a new acceptance test case to cover the new code. 
Closes #886
=> fix: wildcard based branch protection config fails to apply

tests/acceptance/standard/test_variables.py
GitLab API behaviour changed in current latest version (17.7.0) for listing project ci variables. This is causing test failure and blocking changes from merging. The API changes do not have any breaking impact for gitlabform. So, makring the currently failing test to be skipped. It can be re-enabled again based on findings from the issue created in GitLab's backlog at https://gitlab.com/gitlab-org/gitlab/-/issues/511237
closes #908
=> test: mark 'TestVariables::test__builds_disabled' as skipped

gitlabform/gitlab/__init__.py, gitlabform/gitlab/python_gitlab.py, gitlabform/processors/group/group_members_processor.py, gitlabform/processors/project/branches_processor.py, gitlabform/processors/project/members_processor.py, gitlabform/processors/project/tags_processor.py, setup.py, tests/unit/gitlab/test_python_gitlab.py
- graph ql GET only needs Guest+ permissions
- REST requires significantly higher permission sets which not all users maybe comfortable running with
- better error handling for missing Users
=> refactor: use graphql to get member_roles to reduce permission level required

dev/Dockerfile, dev/tests.Dockerfile
* Python images based on Alpine 3.18 are unmaintained (last update: 2024-04-09)
* Thus we should switch to images based on Alpine 3.21
=> chore: update base image to Alpine 3.21

gitlabform/gitlab/projects.py, gitlabform/processors/project/project_settings_processor.py
This PR refactors the code so that `project_settings` config is processed using python-gitlab library.
By moving the processor from `SingleEntityProcessor` to  `AbstractProcessor`, the change is made easily. But it looses the "diff print", which logs the configs as before vs after. I suppose that could be viewed as blocker for this PR.
The diff logging hasn't been globally supported for all the processors. I imagine it can re-implemented differently to support all processors, but that's a bigger task and probably should be done separately.
closes #927
=> refactor: update 'project_settings_processor' to use python-gitlab

.github/dependabot.yml
There are currently 2 packages required from python -gitlab. Dependabot opens separate PR for updating their versions but they fail to install due to conflicts. See issue #934.
This change updates the config so that python-gitlab packages are updated together in a single PR. That should help us easily stay up-to-date with newer release of that package, without needing to manually perform update.
closes #934
=> chore(ci): configure dependabot to group python-gitlab packages

.github/dependabot.yml
I think the previous attempt in #935 for grouping python-gitlab packages together by dependabot PR was incomplete. I re-triggered dependabot but it didn't seem to resolve the issue mentioned in #934. I suspect the pattern for selecting which packages to be groped was not correct.
This PR uses a glob pattern instead of a static string to specify that python-gitlab packages should be grouped together. Not sure how to test this though without going through reproducing the issue elsewhere and testing the fix, which is kind of a lot of work.
=> chore(ci): fix dependabot config group package pattern

gitlabform/configuration/groups.py, tests/unit/configuration/test_skip_groups_skip_projects.py
I discovered that `skip_groups` doesn't work for subgroups. I saw that there is also an open issue.
This PR should fix this.
Fixes #275
=> fix: skip_groups doesn't work for subgroup

gitlabform/processors/project/project_settings_processor.py, tests/acceptance/standard/test_project_settings.py
If the `project_settings` config does not specify `topics` attribute, any topics added manually are being removed. This is bug introduced in v4.1.2. This change reproduces the bug and fixes it so that manually managed topics configs are not removed.
fixes #946
=> fix: project topics should not be removed if topics are not in the config

gitlabform/gitlab/project_merge_requests_approvals.py, gitlabform/processors/project/merge_requests_approvals.py
This PR refactors the logic that processes `merge_requests_approvals` section in a config for managing a project's MR approval settings. The code has been refactored to use python-gitlab as part of the effort of moving the project to use that library instead of relying on homegrown logic.
closes #928
=> refactor: migrate 'merge_requests_approvals' processor to python-gitlab

tests/acceptance/standard/test_files.py
The acceptance test case named `test__set_file_strongly_protected_branch` in `TestFiles` class has been unstable for a few months. This affects the CI process. Most PRs randomly fails because of failure from this test case. This impacts the stability of the project development - can be confusing for contributors when unrelated failures like this occurs.
The failure occurs when the test attempts to validate if a protected branch remains protected after a file update in that branch is performed. I suspect the reason is the tests are running against a GitLab environment running in a container. Either due to resources or GitLab's updates, protecting a branch takes longer than it did before. That's why assertion fails to validate that the branch remains protected.
The change in this PR adds a …
=> tests: stablize intermittent failure from TestFiles acceptance tests

gitlabform/gitlab/__init__.py
This PR adds support for a new out-of-the-box role introduced by GitLab in version 17.7. The role is named 'Planner'.
Added a new enum in the GitLabForm's access level so that the new role can be used or referenced in the gitlabform config.
Docs:
- [GitLab's roles](https://docs.gitlab.com/user/permissions/#roles)
- [GitLab's access level values](https://docs.gitlab.com/api/access_requests/#valid-access-levels)
fixes #980
=> feat: add support for 'Planner' role

docs/changelog.md
This PR fixes the changelog for v4.2.0. Original changelog had some duplicate information from prior version and also missed some other entries. Updates from this PR should make it more accurate.
After this PR is merged, we should manually copy/paste the updated changelog to existing github release details: https://github.com/gitlabform/gitlabform/releases/tag/v4.2.0
=> docs: fix changelog for v4.2.0

docs/contrib/implementation_design.md
as decided in https://github.com/gitlabform/gitlabform/issues/73
This should prevent cases like https://github.com/gitlabform/gitlabform/pull/987#discussion_r2019786718
=> Inform future contributors that they should use python-gitlab

gitlabform/processors/util/labels_processor.py
We have some errors in our gitlab form logging with verbose on:
```
Processing section 'group_labels'
Warning: Error occurred while processing group dwp/secure-development, exception:
404: 404 Label Not Found
```
There's nothing there for us to use to identify the problematic label.
This MR adds one extra verbose log line to assist with identification and ensures labels_processor respects "Verbose" setting by using the cli_ui utility not logging
=> fix: improve logging for labels processor

gitlabform/processors/util/labels_processor.py, tests/acceptance/conftest.py, tests/acceptance/standard/test_group_labels.py
If a label is set on the parent group, and enforce: true is used in the config, then the subgroup label processing attempts to delete the label from the parent group, resulting in a 404 Label not found (as it is not present directly on the subgroup)
=> fix: labels_processor attempts to delete labels set on parent group(s)

gitlabform/processors/project/members_processor.py
I've seen while I worked on another PR that the verbose output doesn't work as intended e.g.:
> Processing user 'testuser'...
> http://localhost:80 "GET /api/v4/users?username=testuser HTTP/1.1" 200 None
> http://localhost:80 "GET /api/v4/users/35 HTTP/1.1" 200 None
> Nothing to change for user '%s' - same config now as to set. testuser
It looks like the verbose does not handle the %s accordingly, thats why I changed it to format strings instead and now it looks like intended:
> Processing user 'testuser'...
> http://localhost:80 "GET /api/v4/users?username=testuser HTTP/1.1" 200 None
> http://localhost:80 "GET /api/v4/users/35 HTTP/1.1" 200 None
> Nothing to change for user 'testuser' - same config now as to set.
If wanted I could look through the whole project and replace them, but not …
=> Fix: verbose output for members_processor

docs/reference/job_token_scope.md, tests/acceptance/standard/test_job_token_scope.py
In a recent major release of GitLab (v18), the CI Job token scope
related setting introduced breaking changes. Going forward, the
option to configure 'limit access to this project' has been removed
and it's enabled by default. However, this option can be restored
by GitLab admin from an instance level setting.
See the [breaking change announcement](https://docs.gitlab.com/update/deprecations/?removal_milestone=18.0&breaking_only=true#cicd-job-token---authorized-groups-and-projects-allowlist-enforcement)
for more details.
After GitLab v18, the test case for gitlabform validating if the
setting mentioned above can be 'disabled', began to fail. This is
because the setting could no longer be configured. This change adds
necessary logic in the test case so that instance level setting is …
=> test: fix test case for job token scope

docs/index.md
* configuration-as-code is a common term and the indefinite article in front of code had me read the line three times.
=> docs: update intro using common term

dev/gitlab.rb, tests/acceptance/premium/test_group_ldap_links.py
It seems we never had any acceptance tests for group ldap links. This PR adds some basic tests - could be expanded in future if needed. It can be helpful for debugging fixing ldap config related issues.
To enable ldap related API endpoints in GitLab for running the tests, gitlab's config needed to be updated by adding a dummy ldap server configuration. It doesn't need to be an active/real server - just the presence of the config is necessary for the relevant API to be available.
Disabled the option to allow login using ldap in the UI when the dev container is started up. This is to help avoid confusions during local development because ldap login becomes the default option and that won't work since there aren't any real ldap server in local dev mode.
=> test: add acceptance test for group ldap links config processor

docs/reference/settings.md, gitlabform/processors/project/project_settings_processor.py, tests/acceptance/conftest.py, tests/acceptance/premium/test_group_settings.py, tests/acceptance/ultimate/test_group_settings.py, tests/acceptance/ultimate/test_project_settings.py
For Groups: the REST api just works
For Projects: Gitlab only supply the option to toggle via their GraphQL api - so that is implemented via python-gitlab
=> feat: add support for duo_features_enabled at project_settings level
