config.yml
gitlabform/gitlab/__init__.py
gitlabform/gitlab/branches.py
gitlabform/gitlab/commits.py
gitlabform/gitlab/core.py
gitlabform/gitlab/keys.py
gitlabform/gitlab/merge_requests.py
gitlabform/gitlab/projects.py
gitlabform/gitlab/repositories.py
gitlabform/gitlab/services.py
gitlabform/gitlab/tags.py
gitlabform/gitlabform/core.py

Migrate to API v4

---

config.yml
gitlabform/gitlab/projects.py
gitlabform/gitlabform/core.py

TODO: add some testing support.

Support project push rules

---

README.md
config.yml
gitlabform/configuration/core.py
gitlabform/gitlab/core.py
gitlabform/gitlabform/core.py
setup.py

I needed that feature ad hoc and thought that you might like it. ;)

integrate gitlabform with jinja2

---

gitlabform/gitlabform/core.py

strict flag works for branches and tags

Update CLI help message

---

config.yml

* Fix incorrect quites used for string with escapes
* Switch to doublequotes where character escaping is not required

Reformat example config

---

config.yml
gitlabform/configuration/projects_and_groups.py
gitlabform/gitlab/groups.py
gitlabform/gitlabform/core.py
pytest.ini

This PR adds:
* support for processing recursively all projects within group if it contains subgroups with other projects,
* support for configuring group-level and subgroup-level configs - they will be merged.

Add full subgroups support

---

config.yml
gitlabform/gitlab/branches.py
gitlabform/gitlabform/core.py
gitlabform/gitlabform/test/test_branches.py

Could you please take a look at my PR?

fix: #27 - Implement the "protected branches" API endpoint

---

CONTRIBUTING.md
gitlabform/gitlabform/core.py
gitlabform/gitlabform/test/test_files.py

This should fix: https://github.com/egnyte/gitlabform/issues/96
I've also added some tests.

Fix interaction between new protected branch API and files

---

CONTRIBUTING.md
gitlabform/gitlab/projects.py

Fixes https://github.com/egnyte/gitlabform/issues/114

Fix project settings save by using json payload

---

config.yml
gitlabform/gitlabform/core.py

I've implemented the flag, the argument, and the block that will catch the first error with a message to exit gracefully. I had trouble getting set up in order to render the change and fully test it. Can you see if I am doing something wrong here?

First error exit

---

gitlabform/gitlabform/processors/project/schedules_processor.py

Fixing https://github.com/egnyte/gitlabform/issues/162

fix: #162 - Allow schedule variables to be empty

---

config.yml

I figured that a typical example of what you want for the default branch is missing.

Add example for typical protection of "main" (aka "master")

---

docs/IMPLEMENTATION_DESIGN.md

- correct spelling
- correct grammar
- propose md structure
- create stronger intent
- improve readabilityity

(docs) update /main/docs/IMPLEMENTATION_DESIGN.md

---

config.yml

Add example how to delete existing schedule.

Update config.yml with shedule deletion example

---

gitlabform/gitlab/groups.py
gitlabform/gitlab/projects.py
gitlabform/gitlabform/core.py

Add --skip-archived-projects option

---

gitlabform/configuration/projects_and_groups.py
gitlabform/configuration/test/test_projects_and_groups.py

Do deep merges of configuration

---

gitlabform/gitlabform/processors/util/branch_protector.py

Skip branch unprotect/protect if the same values are already set.
This will fix egnyte#178

feat: skip branch unprotect/protect if values are unchanged

---

config.yml
gitlabform/configuration/case_insensitivity.py
gitlabform/configuration/core.py
tests/unit/configuration/test_skip_groups_skip_projects.py

#276 Add wildcard support for skip_groups and skip_projects

---

CHANGELOG.md
config.yml
gitlabform/configuration/core.py
gitlabform/core.py
gitlabform/filter.py
gitlabform/gitlab/__init__.py
gitlabform/gitlab/core.py
gitlabform/processors/project/project_settings_processor.py
gitlabform/transform.py
setup.py
tests/acceptance/test_branches.py
tests/acceptance/test_files.py
tests/acceptance/test_group_members_groups.py
tests/acceptance/test_group_members_users.py
tests/acceptance/test_members.py
tests/acceptance/test_tags.py
tests/unit/configuration/test_yaml_version.py
tests/unit/test_transform.py

Start accepting access levels names

---

README.md

Added logo of Elastic Path to "Used by" section of readme.

chore: add Elastic Path logo in readme

---

docs/features.md
docs/reference/resource_group.md
gitlabform/gitlab/__init__.py
gitlabform/gitlab/resource_group.py
gitlabform/processors/project/__init__.py
gitlabform/processors/project/resource_group_processor.py
mkdocs.yml
tests/acceptance/test_resource_groups.py

Added resource group for issue #341.
Example usage:
```
resource_group:
production:
process_mode: oldest_first
```

Add Resource Group API #341

---

gitlabform/gitlab/variables.py
gitlabform/processors/defining_keys.py
gitlabform/processors/project/variables_processor.py
tests/acceptance/test_variables.py

Make specifing environment for variables work (again?)

---

docs/reference/badges.md
docs/reference/ci_cd_variables.md
docs/reference/deploy_keys.md
docs/reference/group_ldap_links.md
gitlabform/processors/multiple_entities_processor.py
setup.py
tests/acceptance/conftest.py
tests/acceptance/test_badges.py
tests/acceptance/test_deploy_keys.py
tests/acceptance/test_deploy_keys_all_projects.py

Add enforce: true support to group badges, group LDAP links, group variables, badges, deploy keys, variables

---

gitlabform/processors/project/merge_requests_processor.py
tests/acceptance/conftest.py
tests/acceptance/standard/test_merge_request_approvers.py

Preparation to implement #388 and #95

Restore merge request approvers tests

---

docs/reference/protected_environments.md
gitlabform/core.py
gitlabform/transform.py
tests/acceptance/conftest.py
tests/acceptance/premium/test_protected_environments.py
tests/unit/test_transform.py

https://github.com/gitlabform/gitlabform/pull/423#issuecomment-1296915602

Added ImplicitNameTransformer

---

gitlabform/processors/project/files_processor.py
tests/acceptance/standard/test_files.py
tests/acceptance/standard/test_files_templates.py

Don't strip trailing new lines from files (fix #451)

---

gitlabform/configuration/transform.py
tests/acceptance/premium/test_protected_environments.py

Add support for group name in protecting environment

---

docs/reference/members.md

Updated documentation to elaborate the behaviour

---

docs/reference/index.md
docs/reference/pipeline_schedules.md

Updated documentation and adjusted some wording to keep consistency

#535 Documentation updates to Pipeline schedules & Breaking inheritance

---

gitlabform/processors/group/group_members_processor.py
tests/acceptance/standard/test_group_members_groups.py

fix: ignore keep_bots from users list for group membership

---

.github/workflows/linter-and-tests.yml
.github/workflows/pr-linter-and-tests.yml
.github/workflows/publish-docs.yml
.github/workflows/publish-to-dockerhub.yml
.github/workflows/publish-to-pypi.yml
dev/Dockerfile
dev/tests.Dockerfile
docs/requirements.md
setup.py

and update base Docker images to Alpine 3.18

Add support for Python 3.12

---

docs/reference/merge_requests.md

It ain't much but it's honest work.

docs: fix branches keyword in MR approval rules

---

.pre-commit-config.yaml
gitlabform/gitlab/__init__.py
gitlabform/gitlab/groups.py
gitlabform/gitlab/members.py
gitlabform/gitlab/python_gitlab.py
gitlabform/processors/abstract_processor.py
gitlabform/processors/group/group_members_processor.py
gitlabform/processors/project/tags_processor.py

Closes https://github.com/gitlabform/gitlabform/issues/633

refactor: migrate `group_members` configuration to use python-gitlab

---

gitlabform/processors/group/group_members_processor.py
gitlabform/processors/project/hooks_processor.py

Fixes https://github.com/gitlabform/gitlabform/issues/732

fix: iterates through group members

---

README.md
docs/features.md
docs/reference/settings.md
gitlabform/__init__.py
gitlabform/processors/application/__init__.py
gitlabform/processors/application/application_settings_processor.py
tests/acceptance/standard/test_application_settings.py

- Resolves #120
- Uses python-gitlab to modify application settings of a GitLab instance

feat: add support for Application Settings

---

docs/reference/resource_groups.md
gitlabform/processors/project/resource_groups_processor.py
tests/acceptance/standard/test_resource_groups.py

feat: add option to not fail if configured resource group does not exist

---

gitlabform/processors/project/variables_processor.py

fix: VariablesProcessor._print_diff() got an unexpected keyword argument 'diff_only_changed'

---

docs/automation.md

Fix Gitlab System hooks doc link

docs: Fix Gitlab System hooks doc link

---

gitlabform/configuration/transform.py
gitlabform/gitlab/python_gitlab.py
gitlabform/processors/group/group_members_processor.py
gitlabform/processors/project/branches_processor.py
gitlabform/processors/project/members_processor.py
gitlabform/processors/project/tags_processor.py

- the get user by username is already cached
- adds extra logging to help users debug effectively

fix: remove caching on get_user_id_cached

---

dev/run_gitlab_in_docker.sh

Make the dev script a bit more configurable by providing cmd line options:
--help                  Display this help message.
--gitlab-version <version> Specify the GitLab version to deploy (default: latest).
--gitlab-flavor <flavor> Specify the GitLab flavor to deploy ("ce" or\"ee"). Default is "ee".
--cpus <value>          Limit CPU usage (e.g., 0.5, 2, etc.). Default: no limit.
--memory <value>        Limit memory usage (e.g., 512m, 2g, etc.). Default: no limit.

chore(dev): add options gitlab-ce etc  to run_gitlab_docker

---

docs/changelog.md

Added missing entries in the changelog and reformatted for consistency with previous changelogs. Once it's approved and merged, we should manually update the release in github release with this change.

docs: update v4.1.2 changelog

---

tests/acceptance/conftest.py
tests/acceptance/premium/test_merge_request_approval_rules.py
tests/acceptance/standard/test_group_members_users.py

test: fix issues with eventual consistency in tests and cover an mr_approval_rules use case

---

gitlabform/processors/util/labels_processor.py
tests/acceptance/standard/test_group_labels.py

- failing acceptance test added / ran
- fix implemented
- closes #1006

fix: labels in parent groups not taken into consideration when applying labels

---

docs/running.md
gitlabform/__init__.py
gitlabform/processors/__init__.py
tests/acceptance/standard/test_running.py
tests/unit/processors/test_abstract_processors.py

feat: implement "exclude-sections" CLI parameter

---

tests/acceptance/premium/test_branches.py
tests/acceptance/standard/test_branches.py

More accurately tests:
- https://github.com/gitlabform/gitlabform/issues/1061
- https://github.com/gitlabform/gitlabform/issues/1034

test: improve branch protection tests
